export { Landing } from './Landing';
export { Courses } from './Courses';
export { CourseDetail } from './CourseDetail';
export { LiveClass } from './LiveClass';
export { Dashboard } from './Dashboard';
export { Payment } from './Payment';
export { Profile } from './Profile';
export { Enrollment } from './Enrollment';
export { CoursePlay } from './CoursePlay';
